// <auto-generated />
using System;
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20220330000746_SetForDateTime")]
    partial class SetForDateTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Author = "Sam Murk",
                            Body = "A blog post about the challenges of working outside the box, and creating something unique",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 79, DateTimeKind.Local).AddTicks(6600)
                        },
                        new
                        {
                            MessageId = 2,
                            Author = "Matthew Elderberry",
                            Body = "The most extra ordinary blog you've ever come across",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 80, DateTimeKind.Local).AddTicks(3000)
                        },
                        new
                        {
                            MessageId = 3,
                            Author = "Tim Roth",
                            Body = "As borring as it gets. You do not want to read this!",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 80, DateTimeKind.Local).AddTicks(3480)
                        },
                        new
                        {
                            MessageId = 4,
                            Author = "Jane Pickered",
                            Body = "If I was a fruit I would ne a mango",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 80, DateTimeKind.Local).AddTicks(3490)
                        },
                        new
                        {
                            MessageId = 5,
                            Author = "Victoria fincert",
                            Body = "Please trust yourself. No one knows you better than yourself",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 80, DateTimeKind.Local).AddTicks(3500)
                        },
                        new
                        {
                            MessageId = 6,
                            Author = "Jossi Brown",
                            Body = "Life is too short for what if's",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 80, DateTimeKind.Local).AddTicks(3510)
                        },
                        new
                        {
                            MessageId = 7,
                            Author = "Mel Gibson",
                            Body = "this is a test",
                            DatePublished = new DateTime(2022, 3, 29, 17, 7, 46, 80, DateTimeKind.Local).AddTicks(3520)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
