// <auto-generated />
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20220328211438_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Author = "Sam Murk",
                            Body = "A blog post about the challenges of working outside the box, and creating something unique"
                        },
                        new
                        {
                            MessageId = 2,
                            Author = "Matthew Elderberry",
                            Body = "The most extra ordinary blog you've ever come across"
                        },
                        new
                        {
                            MessageId = 3,
                            Author = "Tim Roth",
                            Body = "As borring as it gets. You do not want to read this!"
                        },
                        new
                        {
                            MessageId = 4,
                            Author = "Jane Pickered",
                            Body = "If I was a fruit I would ne a mango"
                        },
                        new
                        {
                            MessageId = 5,
                            Author = "Victoria fincert",
                            Body = "Please trust yourself. No one knows you better than yourself"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
